---
- name: Install packages
  apt:
   name:
      # for checking .sh file syntax - shellcheck
      # https://github.com/koalaman/shellcheck
      # may require also https://github.com/koalaman/shellcheck#in-your-editor
     - shellcheck

      # pyqt5 support for python3 (not a critical package)
     - python3-pyqt5 #pygt4 is done in Ubuntu 20, is in Ubuntu 18 LTS

      # show tree structure
      # https://stackoverflow.com/questions/3455625/linux-command-to-print-directory-structure-in-the-form-of-a-tree
     - tree

      # checker of disk health
      # S.M.A.R.T. monitoring tool
     - gsmartcontrol

      # change partitions etc
     - gparted

     # disk usage display
     - baobab

     # temperature graph - https://askubuntu.com/a/628124/349903
     - psensor

     # support for video processing
     - ffmpeg

     # traceroute command
     - traceroute

     # browsing sqlite
     - sqlitebrowser

     # browsing databases
     - phpmyadmin
   force_apt_get: yes
